name: exploring variables and secrets

on: push

env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME:
    IMAGE_NAME: github-actions-nginx

jobs:
    
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: docker build
              run: docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

            - name: Docker login
              run: docker login --username=DOCKER_USERNAME --password=securePassword

            - name: docker publish
              run: docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest


    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
            - name: docker run
              run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest