name: Let's generate

on: push

jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
            - name: Install cowsay
              run: sudo apt install cowsay -y

            - name: execute cowsay
              run: cowsay "Hellooo mooo I'mma coww" >> cow.txt

            - name: uploading my cow file
              uses: actions/upload-artifact@v4
              with:
                name: cow-file
                path: cow.txt

    test_job:
        needs: build_job
        runs-on: ubuntu-latest
        steps:
            - name: downloading my cow file
              uses: actions/download-artifact@v4
              with:
                name: cow-file         

            - name: test file exists
              run: grep -i "cow" cow.txt

    deploy_job:
        needs: [test_job]
        runs-on: ubuntu-latest
        steps:

            - name: downloading my cow file
              uses: actions/download-artifact@v4
              with:
                name: cow-file   

            - name: read file
              run: cat cow.txt

            - name: Deploy
              run: echo Deployinh...
